// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzaomkjiujxdygchurli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YW9ta2ppdWp4ZHlnY2h1cmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzUwNzgsImV4cCI6MjA3MjMxMTA3OH0.iTej-K-Hvx2rDKiE21ScZ90tbyxxOo-xx9gJmEC7Gsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});